### PR TITLE
Modify (correct?) path separator & add TensorFlow libraries & test models

### PR DESCRIPTION
**Pull request by OOHehir**
On my system (Linux Mint) the path separator was breaking the build

### CODE REVIEW

**Comment by OOHehir** [comment]
This PR adds an initial framework for Tensorflow, including libraries & test models, it compiles satisfactorily but a significant issue exists, memory. Currently I'm getting the build error:

Advanced Memory Usage is available via "PlatformIO Home > Project Inspect"
Error: The program size (1469621 bytes) is greater than maximum allowed (1310720 bytes)
RAM:   [==        ]  16.6% (used 54300 bytes from 327680 bytes)
Flash: [====*** [checkprogsize] Explicit exit, status 1
======]  112.1% (used 1469621 bytes from 1310720 bytes)

From what I can remember memory usage was at around 87% before adding this code.

**Comment by LIFsCode** [comment]
@OOHehir I also added you as a contributer to the project. You could push your code to either a separate branch (suggest feature/tfliteModel) in this repo, or keep it up with the pull request, whatever you prefer

**Comment by OOHehir** [comment]
Many thanks!

**Comment by OOHehir** [comment]
Change of plans, going to add Edge Impulse framework instead

**Pull request closed without merging**
